/**
 * Load and resolve market capitalization data for entity nodes.
 *
 * The static JSON at /data/market-caps.json is generated by scripts/fetch-market-caps.ts.
 * It contains:
 *   - tickers: { [symbol]: { ticker, market_cap, name, fetched_at } }
 *   - nameIndex: { [name_fragment]: ticker }
 *
 * This module provides a lookup function: given an entity display name,
 * return its market cap (or null if not a public stock).
 */

interface MarketCapEntry {
  ticker: string
  market_cap: number
  name: string
  fetched_at: string
}

interface MarketCapFile {
  tickers: Record<string, MarketCapEntry>
  nameIndex: Record<string, string>
}

let cached: MarketCapFile | null = null

export async function loadMarketCaps(): Promise<MarketCapFile> {
  if (cached) return cached

  const resp = await fetch('/data/market-caps.json')
  if (!resp.ok) {
    console.warn('Failed to load market-caps.json:', resp.status)
    cached = { tickers: {}, nameIndex: {} }
    return cached
  }

  cached = (await resp.json()) as MarketCapFile
  return cached
}

/**
 * Look up market cap for an entity name.
 * Returns market cap in dollars, or null if entity is not a recognized public stock.
 */
export function getMarketCap(entityName: string, data: MarketCapFile): number | null {
  const lower = entityName.toLowerCase().replace(/[,.]/g, '').replace(/\s+/g, ' ')

  // Try matching against the nameIndex (name fragment -> ticker)
  for (const [fragment, ticker] of Object.entries(data.nameIndex)) {
    if (lower.includes(fragment)) {
      const entry = data.tickers[ticker]
      if (entry) return entry.market_cap
    }
  }

  // Try extracting a ticker suffix like "Apple Inc (AAPL)"
  const tickerMatch = entityName.match(/\(([A-Z]{1,5})\)\s*$/)
  if (tickerMatch) {
    const entry = data.tickers[tickerMatch[1]]
    if (entry) return entry.market_cap
  }

  return null
}
